### ISSUE TITLE
Program doesn't run

### ISSUE THREAD

**Issue by J-C-O** [offenesdresden/Luftqualitaet-src#3]
Hi, i try to run this program, i use this command to start the program
python luftsachsen.py --data-dir data/ --git False
But i get this error:
C:\Users\Julius\Documents\GitHub\Luftqualitaet-src>python luftsachsen.py --data-dir data/ --git False
Traceback (most recent call last):
  File "luftsachsen.py", line 96, in <module>
    use_git = options.use_git)
  File "luftsachsen.py", line 33, in main
    out_dir = raw_dir, basedir = basedir)
  File "C:\Users\Julius\Documents\GitHub\Luftqualitaet-src\AirImport\importer.py", line 188, in main
    h.get_live_data(periods())
  File "C:\Users\Julius\Documents\GitHub\Luftqualitaet-src\AirImport\importer.py", line 52, in get_live_data
    self.read_stations()
  File "C:\Users\Julius\Documents\GitHub\Luftqualitaet-src\AirImport\importer.py", line 71, in read_stations
    for i in stations.find_all('option'):
AttributeError: 'NoneType' object has no attribute 'find_all'

I don't know what to do, i'm using Python 3.4 and i have installed all the requirements.

**Comment by evilham** [comment]
Hey, it looks like Umwelt Sachsen revamped their site, now it's "pretty", but it doesn't actually seem to work.

I do have a WIP patch that, e.g. reads the stations, but for some reason now the substances can't possibly be listed...
